EatAndFeelGoodMVC/Controllers/HomeController.cs
using EatAndFeelGoodMVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace EatAndFeelGoodMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult City()
        {
            return View();
        }
        public IActionResult Gallery()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

EatAndFeelGoodMVC/Controllers/ReservationController.cs
using EatAndFeelGoodMVC.Models;
using EatAndFeelGoodMVC.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EatAndFeelGoodMVC.Controllers
{
    public class ReservationController : Controller
    {
        private readonly ReservationServices _reservationService;

        public ReservationController(ReservationServices reservationService)
        {
            _reservationService = reservationService;
        }

        // GET: Homework
        public ActionResult AddReservation()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddReservation(Reservation reservation)
        {
            try
            {
                _reservationService.AddReservation(reservation);
                _reservationService.Save();
                ModelState.Clear();
                ViewData["Message"] = "Success";
            }
            catch
            {
                ViewData["Message"] = "Error";
            }
            return View();
        }
    }

}

EatAndFeelGoodMVC/Views/Home/City.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "City";
}

<!-- special -->
<div class="special">
    <div class="container">
        <div class="special-heading">
            <h2 class="tittle-t"><span>City</span> Romania</h2>
        </div>
        <div class="special-grids">
            <div class="col-md-4 special-grid">
                <div class="col-md-6 special-img">
                    <div class="special-text effect-1">
                        <h4>@Html.ActionLink("Craiova", "AddReservation", "Reservation")</h4>
                    </div>
                </div>
                <div class="col-md-6 agileits-special-info">
                    <h4>Craiova</h4>
                    <p>Ideal food</p>
                </div>
                <div class="clearfix"> </div>
            </div>
            <div class="col-md-4 special-grid">
                <div class="col-md-6 special-img city-img">
                    <div class="special-text effect-1">
                        <h4>@Html.ActionLink("Bucuresti", "City")</h4>
                    </div>
                </div>
                <div class="col-md-6 agileits-special-info">
                    <h4>Bucuresti</h4>
                    <p>Party Night</p>
                </div>
                <div class="clearfix"> </div>
            </div>
            <div class="col-md-4 special-grid">
                <div class="col-md-6 special-img city-img1">
                    <div class="special-text effect-1">
                        <h4>@Html.ActionLink("Brasov", "City")</h4>
                    </div>
                </div>
                <div class="col-md-6 agileits-special-info">
                    <h4>Brasov</h4>
                    <p>Food</p>
                </div>
                <div class="clearfix"> </div>
            </div>
            <div class="col-md-4 special-grid">
                <div class="col-md-6 agileits-special-info">
                    <h4>Cluj-Napoca</h4>
                    <p>Food</p>
                </div>
                <div class="col-md-6 special-img city-img2">
                    <div class="special-text effect-1">
                        <h4>@Html.ActionLink("Cluj-Napoca", "City")</h4>
                    </div>
                </div>
                <div class="clearfix"> </div>
            </div>
            <div class="col-md-4 special-grid">
                <div class="col-md-6 agileits-special-info">
                    <h4>Soon</h4>
                    <p>Food</p>
                </div>
                <div class="col-md-6 special-img city-img3">
                    <div class="special-text effect-1">
                        <h4>@Html.ActionLink("Soon", "City")</h4>
                    </div>
                </div>
                <div class="clearfix"> </div>
            </div>
            <div class="col-md-4 special-grid">
                <div class="col-md-6 agileits-special-info">
                    <h4>Soon</h4>
                    <p>Food</p>
                </div>
                <div class="col-md-6 special-img city-img4">
                    <div class="special-text effect-1">
                        <h4>@Html.ActionLink("Soon", "City")</h4>
                    </div>
                </div>
                <div class="clearfix"> </div>
            </div>
            <div class="clearfix"> </div>
        </div>
    </div>
</div>
<!-- //special -->
<!--services-section-->
<div class="clearfix"></div>
<!--//services-section-->

EatAndFeelGoodMVC/Views/Home/Gallery.cshtml
@{
    ViewData["Title"] = "Gallery";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- gallery -->
<div class="gallery">
    <div class="container">
        <h2 class="tittle-t">Gallery</h2>
        <div class="gallery-grids">
            <div class="col-md-4 gallery-grid wow fadeInUp animated" data-wow-delay=".5s">
                <div class="grid">
                    <figure class="effect-apollo">
                        <a class="example-image-link" href="~/images/g1.jpg" data-lightbox="example-set" data-title="">
                            <img src="~/images/g1.jpg" alt="" />
                            <figcaption>
                                <h3>Craiova</h3>
                                <p>Excelsior</p>
                            </figcaption>
                        </a>
                    </figure>
                </div>
            </div>
            <div class="col-md-4 gallery-grid wow fadeInUp animated" data-wow-delay=".5s">
                <div class="grid">
                    <figure class="effect-apollo">
                        <a class="example-image-link" href="~/images/g2.jpg" data-lightbox="example-set" data-title="">
                            <img src="~/images/g2.jpg" alt="" />
                            <figcaption>
                                <h3>Craiova</h3>
                                <p>Smart Pub</p>
                            </figcaption>
                        </a>
                    </figure>
                </div>
            </div>
            <div class="col-md-4 gallery-grid wow fadeInUp animated" data-wow-delay=".5s">
                <div class="grid">
                    <figure class="effect-apollo">
                        <a class="example-image-link" href="~/images/g3.jpg" data-lightbox="example-set" data-title="">
                            <img src="~/images/g3.jpg" alt="" />
                            <figcaption>
                                <h3>Bucuresti</h3>
                                <p>Nor<br>Sky Casual Restaurant</p>
                            </figcaption>
                        </a>
                    </figure>
                </div>
            </div>
            <div class="col-md-4 gallery-grid wow fadeInUp animated" data-wow-delay=".5s">
                <div class="grid">
                    <figure class="effect-apollo">
                        <a class="example-image-link" href="~/images/g4.jpg" data-lightbox="example-set" data-title="">
                            <img src="~/images/g4.jpg" alt="" />
                            <figcaption>
                                <h3>Bucuresti</h3>
                                <p>Biutiful<br>Downtown</p>
                            </figcaption>
                        </a>
                    </figure>
                </div>
            </div>
            <div class="col-md-4 gallery-grid wow fadeInUp animated" data-wow-delay=".5s">
                <div class="grid">
                    <figure class="effect-apollo">
                        <a class="example-image-link" href="~/images/g12.jpg" data-lightbox="example-set" data-title="">
                            <img src="~/images/g12.jpg" alt="" />
                            <figcaption>
                                <h3>Cluj-Napoca</h3>
                                <p>Marty</p>
                            </figcaption>
                        </a>
                    </figure>
                </div>
            </div>
            <div class="col-md-4 gallery-grid wow fadeInUp animated" data-wow-delay=".5s">
                <div class="grid">
                    <figure class="effect-apollo">
                        <a class="example-image-link" href="~/images/g6.jpg" data-lightbox="example-set" data-title="">
                            <img src="~/images/g6.jpg" alt="" />
                            <figcaption>
                                <h3>Brasov</h3>
                                <p>Sub Tampa</p>
                            </figcaption>
                        </a>
                    </figure>
                </div>
            </div>



            <div class="clearfix"> </div>
        </div>
    </div>
</div>
<!-- //gallery -->

EatAndFeelGoodMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/Index_Layout.cshtml";
}

<div class="ab-about">
    <div class="container">
        <h3 class="tittle-t"><span>Welcome and </span> Enjoy your meal</h3>
    </div>
</div>
<div class="about" id="about">
    <div class="col-md-6 ab-agile-info">
        <div class="col-md-6 ab-agile-part two">
            <h4>Craiova</h4>
            <img src="images/craiova.jpg" alt=" " class="img-responsive" />
        </div>
        <div class="col-md-6 ab-agile-part two">
            <h4>Bucuresti</h4>
            <img src="images/bucuresti.jpg" alt=" " class="img-responsive" />
        </div>

        <div class="clearfix"></div>
    </div>
</div>
<div class="col-md-6 ab-agile-info">
    <div class="col-md-6 ab-agile-part two">
        <h4>Brasov</h4>
        <img src="images/brasov.jpg" alt=" " class="img-responsive" />
    </div>
    <div class="col-md-6 ab-agile-part two">
        <h4>Cluj-Napoca</h4>
        <img src="images/cluj.jpg" alt=" " class="img-responsive" />
    </div>

</div>

<div class="clearfix"></div>



<!--count-->
<div class="count-agileits">
    <div id="particles-js"></div>

    <div class="count-grids">
        <h3 class="tittle-t">We <span> are not the only one </span> but we are the best</h3>
        <div class="count-bgcolor-ls">
            <div class="col-md-4 count-grid">
                <i class="fa fa-cutlery" aria-hidden="true"></i>
                <div class="count hvr-bounce-to-bottom">
                    <div class='numscroller numscroller-big-bottom' data-slno='1' data-min='0' data-max='250' data-delay='.5' data-increment="1">0</div>
                    <span></span>
                    <h5>Restaurants</h5>
                </div>
            </div>
            <div class="col-md-4 count-grid">
                <i class="fa fa-user-plus" aria-hidden="true"></i>
                <div class="count hvr-bounce-to-bottom">
                    <div class='numscroller numscroller-big-bottom' data-slno='1' data-min='0' data-max='3600' data-delay='.5' data-increment="10">0</div>
                    <span></span>
                    <h5>Members</h5>
                </div>
            </div>
            <div class="col-md-4 count-grid">
                <i class="fa fa-users" aria-hidden="true"></i>
                <div class="count hvr-bounce-to-bottom">
                    <div class='numscroller numscroller-big-bottom' data-slno='1' data-min='0' data-max='4500' data-delay='.5' data-increment="10">0</div>
                    <span></span>
                    <h5>Clients</h5>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</div>
<!--count-->